### ISSUE TITLE
circular references a lot libs\dorf\src\fields\dorf-select.metadata.js -> libs\dorf\src\fields\dorf-select.definition.js -> libs\dorf\src\fields\base\dorf-field.js -> libs\dorf\src\fields\dorf-select.metadata.js

### ISSUE THREAD

**Issue by StartSWest** [mat3e/dorf#6]

**Comment by mat3e** [comment]
Hi, thanks for your input. 

Regarding the name, I wanted to have something short and easy to remember. I know _dorf_ means _village_ in German, but I don't think this is a big issue. Is there any other (worse) translation in some language?

Regarding the dependency. The problem is with this `dorf-field` module. It appeared pretty late and the idea was to have a list of all the out of the box fields. I think I should split this module into 2 - constants and instances. It would solve the issue.

I'm not actively maintaining this library, but I will try to take a look at this, during the weekend.
